# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  domain_name: example.com
  secret_key_base: 1553d0cdf13afbead2a845ca63bd6bfb576d1b4901cb728d8a6e8ff4e62c54e991016737d96a514862781ad00c53a75408fb5886c7b53cf26079de2cc90de257

test:
  secret_key_base: d3cf5dff72f00c7c4dc2d9b6ee8502e41f5078d0f5d9e6243aaa604892c00c8db0ef918ecfce326d88aa2363f1ede6276751d99656bc7acdca74945b5990599d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
